version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    volumes:
    #  - ./configs/elasticsearch/:/usr/share/elasticsearch/config/
      - es_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - nginx
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    networks:
      - elk    
    environment:
      - NGINX_USER=root
      - NGINX_ERROR_LOG_FILE=/var/log/nginx/error.log
      - NGINX_ACCESS_LOG_FILE=/var/log/nginx/access.log 
    restart: always

  logstash:
    image: logstash:7.16.2
    volumes:
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./nginx_logs:/var/log/nginx 
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m" 
    ports:
      - "5044:5044"
      - "5001:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 3

  kibana:
    image: kibana:7.16.2
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test
    networks:
      - elk
    ports:
      - "5601:5601"
    

  beats:
    image: elastic/filebeat:7.16.2
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./nginx_logs:/var/log/nginx:ro
    #  - ./host_metrics_app/:/host_metrics_app/
    # - ./log_gen/:/log_gen/
    networks:
      - elk
    depends_on:
      - elasticsearch
#    depends_on:
#      logstash:
#        condition: service_healthy
    restart: unless-stopped

networks:
  elk:
    driver: bridge
volumes:
  es_data: