version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    networks:
      - elk    
    environment:
      - NGINX_USER=root
      - NGINX_ERROR_LOG_FILE=/var/log/nginx/error.log
      - NGINX_ACCESS_LOG_FILE=/var/log/nginx/access.log 
    restart: always

  logstash:
    image: logstash:7.16.2
    volumes:
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./nginx_logs:/var/log/nginx 
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m" 
    ports:
      - "5044:5044"
      - "5001:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.2
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test
    networks:
      - elk
    ports:
      - "5601:5601"
    

  beats:
    image: elastic/filebeat:8.6.1
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./host_metrics_app/:/host_metrics_app/
      - ./log_gen/:/log_gen/
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
volumes:
  es_data: