server.name: kibana
server.host: "0.0.0.0"
server.publicBaseUrl: "http://localhost:5601"

# Обязательные security-настройки
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "min-32-byte-long-strong-encryption-key" # Замените на свою случайную строку!
xpack.reporting.encryptionKey: "min-32-byte-long-strong-encryption-key"
xpack.security.encryptionKey: "min-32-byte-long-strong-encryption-key"

# Подключение к Elasticsearch
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "test"


# Настройки Fleet и интеграций
xpack.fleet.registryUrl: "https://epr.elastic.co"
xpack.fleet.packages:
  - name: system
    version: latest



